version: '3.8'

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "5290:8080"
    environment:
      - LABEL_STUDIO_HOST=https://annotation.hitec.skynet.coypu.org/
      - LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      - DATABASE=postgres
      - POSTGRE_NAME=labelstudio
      - POSTGRE_USER=labeluser
      - POSTGRE_PASSWORD=labelpass
      - POSTGRE_HOST=labelstudio-db
      - POSTGRE_PORT=5432
    volumes:
      - ./mydata:/label-studio/data
      - ./myfiles:/label-studio/files
    stdin_open: true
    tty: true
    restart: unless-stopped

  labelstudio-db:
    image: postgres:latest
    container_name: labelstudio-db
    environment:
      POSTGRES_DB: labelstudio
      POSTGRES_USER: labeluser
      POSTGRES_PASSWORD: labelpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
